# Makefile for all the folders
#
#
# Author: Adrian Buzatu, 25 Oct 2012

all:
	@echo " " && make -C Helper
	@echo " " && make -C Helper2
	@echo " " && make -C Date
	@echo " " && make -C Vector
	@echo " " && make -C Vector3D
	@echo " " && make -C TemplatedClass
	@echo " " && make -C TemplatedClassStreamer
	@echo " " && make -C testHelloWorld
	@echo " " && make -C testHowLongItRuns
	@echo " " && make -C testCommandLineArguments
	@echo " " && make -C testCommandLineArgumentsWithUsageMethod
	@echo " " && make -C testUseOurSharedLibrary
	@echo " " && make -C testUseOurSharedLibraryThatUsesAnotherSharedLibraryOfOurs
	@echo " " && make -C testReadFromFile
	@echo " " && make -C testWriteToFile
	@echo " " && make -C testFunctionTemplate
	@echo " " && make -C testFunctionOverloading
	@echo " " && make -C testFunctionDefaultValue
	@echo " " && make -C testFunctionPassByReference
	@echo " " && make -C testFunctionPassByPointer
	@echo " " && make -C testStdVector
	@echo " " && make -C testStdMap
	@echo " " && make -C testVector
	@echo " " && make -C testVector3D
	@echo " " && make -C testDate
	@echo " " && make -C testTemplatedClass
	@echo " " && make -C testTemplatedClassStreamer
	@echo " " && echo "done: make for all."
clean:
	@echo " " && make clean -C Helper
	@echo " " && make clean -C Helper2
	@echo " " && make clean -C Date
	@echo " " && make clean -C Vector
	@echo " " && make clean -C Vector3D
	@echo " " && make clean -C TemplatedClass
	@echo " " && make clean -C TemplatedClassStreamer
	@echo " " && make clean -C testHelloWorld
	@echo " " && make clean -C testHowLongItRuns
	@echo " " && make clean -C testCommandLineArguments
	@echo " " && make clean -C testCommandLineArgumentsWithUsageMethod
	@echo " " && make clean -C testUseOurSharedLibrary
	@echo " " && make clean -C testUseOurSharedLibraryThatUsesAnotherSharedLibraryOfOurs
	@echo " " && make clean -C testReadFromFile
	@echo " " && make clean -C testWriteToFile
	@echo " " && make clean -C testFunctionTemplate
	@echo " " && make clean -C testFunctionOverloading
	@echo " " && make clean -C testFunctionDefaultValue
	@echo " " && make clean -C testFunctionPassByReference
	@echo " " && make clean -C testFunctionPassByPointer
	@echo " " && make clean -C testStdVector
	@echo " " && make clean -C testStdMap
	@echo " " && make clean -C testVector
	@echo " " && make clean -C testVector3D
	@echo " " && make clean -C testDate
	@echo " " && make clean -C testTemplatedClass
	@echo " " && make clean -C testTemplatedClassStreamer
	@rm -f *~
	@rm -f \#*
	@echo " " && echo "done: make clean for all."
